// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleAudioBooksPlayer.DAL;

namespace SimpleAudioBooksPlayer.DAL.Migrations
{
    [DbContext(typeof(FilesContext))]
    [Migration("20190602071158_FirstCreate")]
    partial class FirstCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("SimpleAudioBooksPlayer.DAL.LyricFile", b =>
                {
                    b.Property<string>("FilePath")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DbVersion");

                    b.Property<string>("FileName");

                    b.Property<DateTime>("ModifyTime");

                    b.Property<string>("ParentFolderName");

                    b.Property<string>("ParentFolderPath");

                    b.HasKey("FilePath");

                    b.ToTable("LyricFiles");
                });

            modelBuilder.Entity("SimpleAudioBooksPlayer.DAL.MusicFile", b =>
                {
                    b.Property<string>("FilePath")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DbVersion");

                    b.Property<TimeSpan>("Duration");

                    b.Property<string>("FileName");

                    b.Property<DateTime>("ModifyTime");

                    b.Property<string>("ParentFolderName");

                    b.Property<string>("ParentFolderPath");

                    b.Property<string>("Title");

                    b.HasKey("FilePath");

                    b.ToTable("MusicFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
