// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleAudioBooksPlayer.DAL;

namespace SimpleAudioBooksPlayer.DAL.Migrations
{
    [DbContext(typeof(FilesContext))]
    [Migration("20210119114420_Drop_FileModel_Table")]
    partial class Drop_FileModel_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("SimpleAudioBooksPlayer.DAL.ClassItem", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BackgroundColor");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Name");

                    b.HasKey("Index");

                    b.ToTable("ClassList");
                });

            modelBuilder.Entity("SimpleAudioBooksPlayer.DAL.FileGroup", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClassId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("FolderPath");

                    b.Property<bool>("HasCover");

                    b.Property<string>("Name");

                    b.HasKey("Index");

                    b.ToTable("FileGroups");
                });

            modelBuilder.Entity("SimpleAudioBooksPlayer.DAL.PlaybackRecord", b =>
                {
                    b.Property<int>("GroupId");

                    b.Property<string>("CurrentTitle");

                    b.Property<bool>("IsReverse");

                    b.Property<DateTime>("PlayDate");

                    b.Property<TimeSpan>("PlayedTime");

                    b.Property<string>("SortMethod");

                    b.Property<uint>("TrackId");

                    b.HasKey("GroupId");

                    b.ToTable("PlaybackRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
