// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleAudioBooksPlayer.DAL;

namespace SimpleAudioBooksPlayer.DAL.Migrations
{
    [DbContext(typeof(FilesContext))]
    partial class FilesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("SimpleAudioBooksPlayer.DAL.LyricFile", b =>
                {
                    b.Property<string>("FilePath")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DbVersion");

                    b.Property<string>("FileName");

                    b.Property<DateTime>("ModifyTime");

                    b.Property<string>("ParentFolderName");

                    b.Property<string>("ParentFolderPath");

                    b.HasKey("FilePath");

                    b.ToTable("LyricFiles");
                });

            modelBuilder.Entity("SimpleAudioBooksPlayer.DAL.MusicFile", b =>
                {
                    b.Property<string>("FilePath")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DbVersion");

                    b.Property<TimeSpan>("Duration");

                    b.Property<string>("FileName");

                    b.Property<int?>("Index");

                    b.Property<DateTime>("ModifyTime");

                    b.Property<string>("ParentFolderName");

                    b.Property<string>("ParentFolderPath");

                    b.Property<string>("Title");

                    b.HasKey("FilePath");

                    b.HasIndex("Index");

                    b.ToTable("MusicFiles");
                });

            modelBuilder.Entity("SimpleAudioBooksPlayer.DAL.MusicGroup", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("HasCover");

                    b.Property<string>("Name");

                    b.HasKey("Index");

                    b.ToTable("GroupItems");
                });

            modelBuilder.Entity("SimpleAudioBooksPlayer.DAL.MusicFile", b =>
                {
                    b.HasOne("SimpleAudioBooksPlayer.DAL.MusicGroup", "Group")
                        .WithMany()
                        .HasForeignKey("Index");
                });
#pragma warning restore 612, 618
        }
    }
}
